"""Lifecycle email copy for es, fr, de."""

EMAIL_COPY_WESTERN = {
    "es": {
        "welcome": {
            "subject": "Tu viaje nutricional empieza ahora, {{first_name}}",
            "heading": "¡Tu viaje nutricional empieza ahora, {{first_name}}! 🎉",
            "intro": "¡Bienvenido a Nutree! Has dado el primer paso para entender tu nutrición y alcanzar tus metas.",
            "target_label": "Objetivo calórico diario",
            "social_proof": "Únete a más de 10.000 usuarios que registran sus comidas cada día con Nutree.",
            "cta": "Registra Tu Primera Comida",
            "closing": "Una comida a la vez. ¡Tú puedes! 💪",
        },
        "reengagement": {
            "subject": "Guardamos tu progreso, {{first_name}}",
            "heading": "Guardamos tu progreso, {{first_name}} 📊",
            "intro": "Notamos que no has registrado comidas en unos días. Tu racha y tus datos siguen aquí.",
            "streak_label": "días de racha",
            "streak_warning": "¡No dejes que se reinicie!",
            "cta": "Retoma Donde Lo Dejaste",
            "reply_note": "¿Qué te lo impidió? Responde a este email — leemos cada respuesta.",
        },
        "trial_expiring": {
            "subject": "En {{days_left}} días, tus macros se apagan",
            "heading": "En {{days_left}} días, tus macros se apagan ⏰",
            "intro": "Hola {{first_name}}, tu prueba de Nutree termina pronto.",
            "stats_intro": "Esto es lo que has logrado:",
            "meals_label": "Comidas registradas",
            "streak_label": "Días de racha",
            "upgrade_message": "Conserva tu progreso. Mejora ahora y sigue tu camino.",
            "cta": "Mejorar a Premium",
        },
        "trial_cancelled": {
            "subject": "Antes de irte — ¿una pregunta rápida?",
            "heading": "Antes de irte — ¿una pregunta rápida? 🤔",
            "intro": "Hola {{first_name}}, lamentamos que canceles.",
            "feedback_intro": "Nos encantaría saber qué podemos mejorar. ¿Cuál fue la razón principal?",
            "reason_too_expensive": "💰 Muy caro",
            "reason_not_using": "📱 No lo usaba lo suficiente",
            "reason_missing_features": "🔧 Faltan funciones que necesito",
            "reason_other": "💬 Otra razón",
            "pause_heading": "¿Necesitas un descanso?",
            "pause_message": "Puedes pausar tu suscripción 30 días en lugar de cancelar.",
            "pause_link": "Pausar en su lugar",
            "closing": "La puerta siempre está abierta si quieres volver. 💚",
        },
    },
    "fr": {
        "welcome": {
            "subject": "Ton parcours nutrition commence maintenant, {{first_name}}",
            "heading": "Ton parcours nutrition commence maintenant, {{first_name}} ! 🎉",
            "intro": "Bienvenue sur Nutree ! Tu as fait le premier pas pour comprendre ta nutrition et atteindre tes objectifs.",
            "target_label": "Objectif calorique quotidien",
            "social_proof": "Rejoins plus de 10 000 utilisateurs qui suivent leurs repas chaque jour avec Nutree.",
            "cta": "Enregistre Ton Premier Repas",
            "closing": "Un repas à la fois. Tu peux le faire ! 💪",
        },
        "reengagement": {
            "subject": "On a gardé ta progression, {{first_name}}",
            "heading": "On a gardé ta progression, {{first_name}} 📊",
            "intro": "On a remarqué que tu n'as pas enregistré de repas depuis quelques jours. Ta série et tes données t'attendent.",
            "streak_label": "jours de série",
            "streak_warning": "Ne la laisse pas repartir à zéro !",
            "cta": "Reprends Là Où Tu T'étais Arrêté",
            "reply_note": "Qu'est-ce qui t'a bloqué ? Réponds à cet email — on lit chaque message.",
        },
        "trial_expiring": {
            "subject": "Dans {{days_left}} jours, tes macros s'éteignent",
            "heading": "Dans {{days_left}} jours, tes macros s'éteignent ⏰",
            "intro": "Salut {{first_name}}, ton essai Nutree se termine bientôt.",
            "stats_intro": "Voici ce que tu as construit :",
            "meals_label": "Repas enregistrés",
            "streak_label": "Jours de série",
            "upgrade_message": "Garde ta progression. Passe à Premium et continue ton parcours.",
            "cta": "Passer à Premium",
        },
        "trial_cancelled": {
            "subject": "Avant de partir — une petite question ?",
            "heading": "Avant de partir — une petite question ? 🤔",
            "intro": "Salut {{first_name}}, on est désolé de te voir annuler.",
            "feedback_intro": "On aimerait savoir ce qu'on pourrait améliorer. Quelle était la raison principale ?",
            "reason_too_expensive": "💰 Trop cher",
            "reason_not_using": "📱 Pas assez utilisé",
            "reason_missing_features": "🔧 Fonctions manquantes",
            "reason_other": "💬 Autre raison",
            "pause_heading": "Besoin d'une pause ?",
            "pause_message": "Tu peux mettre ton abonnement en pause 30 jours au lieu d'annuler.",
            "pause_link": "Mettre en pause",
            "closing": "La porte reste ouverte si tu veux revenir. 💚",
        },
    },
    "de": {
        "welcome": {
            "subject": "Deine Ernährungsreise startet jetzt, {{first_name}}",
            "heading": "Deine Ernährungsreise startet jetzt, {{first_name}}! 🎉",
            "intro": "Willkommen bei Nutree! Du hast den ersten Schritt gemacht, deine Ernährung zu verstehen und deine Ziele zu erreichen.",
            "target_label": "Tägliches Kalorienziel",
            "social_proof": "Schließe dich über 10.000 Nutzern an, die täglich ihre Mahlzeiten mit Nutree tracken.",
            "cta": "Erste Mahlzeit Loggen",
            "closing": "Eine Mahlzeit nach der anderen. Du schaffst das! 💪",
        },
        "reengagement": {
            "subject": "Wir haben deinen Fortschritt gespeichert, {{first_name}}",
            "heading": "Wir haben deinen Fortschritt gespeichert, {{first_name}} 📊",
            "intro": "Wir haben gemerkt, dass du seit ein paar Tagen keine Mahlzeit geloggt hast. Deine Serie und Daten warten auf dich.",
            "streak_label": "Tage Serie",
            "streak_warning": "Lass sie nicht verfallen!",
            "cta": "Mach Weiter Wo Du Aufgehört Hast",
            "reply_note": "Was hat dich blockiert? Antworte auf diese E-Mail — wir lesen jede Nachricht.",
        },
        "trial_expiring": {
            "subject": "In {{days_left}} Tagen werden deine Makros dunkel",
            "heading": "In {{days_left}} Tagen werden deine Makros dunkel ⏰",
            "intro": "Hey {{first_name}}, deine Nutree-Testphase endet bald.",
            "stats_intro": "Das hast du bisher aufgebaut:",
            "meals_label": "Mahlzeiten geloggt",
            "streak_label": "Tage Serie",
            "upgrade_message": "Behalte deinen Fortschritt. Upgrade jetzt und mach weiter.",
            "cta": "Auf Premium Upgraden",
        },
        "trial_cancelled": {
            "subject": "Bevor du gehst — eine kurze Frage?",
            "heading": "Bevor du gehst — eine kurze Frage? 🤔",
            "intro": "Hey {{first_name}}, schade, dass du kündigst.",
            "feedback_intro": "Wir würden gerne wissen, was wir besser machen können. Was war der Hauptgrund?",
            "reason_too_expensive": "💰 Zu teuer",
            "reason_not_using": "📱 Zu wenig genutzt",
            "reason_missing_features": "🔧 Fehlende Funktionen",
            "reason_other": "💬 Anderer Grund",
            "pause_heading": "Brauchst du eine Pause?",
            "pause_message": "Du kannst dein Abo 30 Tage pausieren statt zu kündigen.",
            "pause_link": "Stattdessen pausieren",
            "closing": "Die Tür steht offen, wenn du zurückkommen willst. 💚",
        },
    },
}
