"""English and Vietnamese lifecycle email copy."""

EMAIL_COPY_EN_VI = {
    "en": {
        "welcome": {
            "subject": "Your nutrition journey starts now, {{first_name}}",
            "heading": "Your nutrition journey starts now, {{first_name}}! 🎉",
            "intro": "Welcome to Nutree! You've taken the first step toward understanding your nutrition and reaching your goals.",
            "target_label": "Daily calorie target",
            "social_proof": "Join 10,000+ users who track their meals daily with Nutree.",
            "cta": "Log Your First Meal",
            "closing": "One meal at a time. You've got this! 💪",
        },
        "reengagement": {
            "subject": "We saved your progress, {{first_name}}",
            "heading": "We saved your progress, {{first_name}} 📊",
            "intro": "We noticed you haven't logged a meal in a few days. Your tracking streak and data are still here, waiting for you.",
            "streak_label": "day streak",
            "streak_warning": "Don't let it reset!",
            "cta": "Pick Up Where You Left Off",
            "reply_note": "What got in the way? Reply to this email — we read every response.",
        },
        "trial_expiring": {
            "subject": "In {{days_left}} days, your macros go dark",
            "heading": "In {{days_left}} days, your macros go dark ⏰",
            "intro": "Hey {{first_name}}, your Nutree trial is ending soon.",
            "stats_intro": "Here's what you've built so far:",
            "meals_label": "Meals logged",
            "streak_label": "Day streak",
            "upgrade_message": "Keep your progress. Upgrade now and continue your journey.",
            "cta": "Upgrade to Premium",
        },
        "trial_cancelled": {
            "subject": "Before you go — one quick question?",
            "heading": "Before you go — one quick question? 🤔",
            "intro": "Hey {{first_name}}, we're sorry to see you cancel.",
            "feedback_intro": "We'd love to know what we could do better. What was the main reason?",
            "reason_too_expensive": "💰 Too expensive",
            "reason_not_using": "📱 Wasn't using it enough",
            "reason_missing_features": "🔧 Missing features I need",
            "reason_other": "💬 Something else",
            "pause_heading": "Need a break instead?",
            "pause_message": "You can pause your subscription for 30 days instead of cancelling.",
            "pause_link": "Pause instead",
            "closing": "The door is always open if you want to come back. 💚",
        },
    },
    "vi": {
        "welcome": {
            "subject": "Hành trình dinh dưỡng của bạn bắt đầu từ hôm nay, {{first_name}}",
            "heading": "Hành trình dinh dưỡng của bạn bắt đầu từ hôm nay, {{first_name}}! 🎉",
            "intro": "Chào mừng đến với Nutree! Bạn đã bước đầu tiên để hiểu dinh dưỡng và đạt mục tiêu của mình.",
            "target_label": "Mục tiêu calo hàng ngày",
            "social_proof": "Tham gia cùng hơn 10.000 người dùng ghi lại bữa ăn mỗi ngày với Nutree.",
            "cta": "Ghi Bữa Ăn Đầu Tiên",
            "closing": "Từng bữa một. Bạn làm được mà! 💪",
        },
        "reengagement": {
            "subject": "Chúng tôi đã lưu tiến trình của bạn, {{first_name}}",
            "heading": "Chúng tôi đã lưu tiến trình của bạn, {{first_name}} 📊",
            "intro": "Chúng tôi thấy bạn chưa ghi bữa ăn vài ngày rồi. Streak và dữ liệu của bạn vẫn còn đây.",
            "streak_label": "ngày streak",
            "streak_warning": "Đừng để nó reset nhé!",
            "cta": "Tiếp Tục Ngay",
            "reply_note": "Điều gì cản trở bạn? Trả lời email này — chúng tôi đọc từng phản hồi.",
        },
        "trial_expiring": {
            "subject": "Còn {{days_left}} ngày nữa là macro của bạn tắt",
            "heading": "Còn {{days_left}} ngày nữa là macro của bạn tắt ⏰",
            "intro": "Chào {{first_name}}, trial Nutree của bạn sắp hết hạn.",
            "stats_intro": "Đây là những gì bạn đã xây dựng:",
            "meals_label": "Bữa ăn đã ghi",
            "streak_label": "Ngày streak",
            "upgrade_message": "Giữ tiến trình của bạn. Nâng cấp ngay và tiếp tục hành trình.",
            "cta": "Nâng Cấp Premium",
        },
        "trial_cancelled": {
            "subject": "Trước khi bạn đi — một câu hỏi nhanh?",
            "heading": "Trước khi bạn đi — một câu hỏi nhanh? 🤔",
            "intro": "Chào {{first_name}}, rất tiếc khi thấy bạn hủy.",
            "feedback_intro": "Chúng tôi muốn biết có thể cải thiện gì. Lý do chính là gì?",
            "reason_too_expensive": "💰 Quá đắt",
            "reason_not_using": "📱 Không dùng đủ",
            "reason_missing_features": "🔧 Thiếu tính năng cần",
            "reason_other": "💬 Lý do khác",
            "pause_heading": "Cần nghỉ một chút?",
            "pause_message": "Bạn có thể tạm dừng gói 30 ngày thay vì hủy.",
            "pause_link": "Tạm dừng thay vì hủy",
            "closing": "Cửa luôn mở nếu bạn muốn quay lại. 💚",
        },
    },
}
