"""Lifecycle email copy for ja and zh."""

EMAIL_COPY_EAST_ASIAN = {
    "ja": {
        "welcome": {
            "subject": "栄養の旅が今始まります、{{first_name}}さん",
            "heading": "栄養の旅が今始まります、{{first_name}}さん！ 🎉",
            "intro": "Nutreeへようこそ！栄養を理解し、目標に近づく第一歩を踏み出しました。",
            "target_label": "1日のカロリー目標",
            "social_proof": "Nutreeで毎日食事を記録する1万人以上のユーザーに参加しよう。",
            "cta": "最初の食事を記録",
            "closing": "一食ずつ。きっとできる！ 💪",
        },
        "reengagement": {
            "subject": "進捗を保存しました、{{first_name}}さん",
            "heading": "進捗を保存しました、{{first_name}}さん 📊",
            "intro": "数日間食事の記録がないようです。ストリークとデータはここに残っています。",
            "streak_label": "日ストリーク",
            "streak_warning": "リセットしないで！",
            "cta": "続きから再開",
            "reply_note": "何が障害になりましたか？このメールに返信してください — すべて読んでいます。",
        },
        "trial_expiring": {
            "subject": "あと{{days_left}}日でマクロが見えなくなります",
            "heading": "あと{{days_left}}日でマクロが見えなくなります ⏰",
            "intro": "こんにちは {{first_name}}さん、Nutreeのトライアルがもうすぐ終了します。",
            "stats_intro": "これまでの成果：",
            "meals_label": "記録した食事",
            "streak_label": "日ストリーク",
            "upgrade_message": "進捗をキープ。今すぐアップグレードして旅を続けよう。",
            "cta": "Premiumにアップグレード",
        },
        "trial_cancelled": {
            "subject": "去る前に — ひとつ質問させて",
            "heading": "去る前に — ひとつ質問させて 🤔",
            "intro": "こんにちは {{first_name}}さん、解約は残念です。",
            "feedback_intro": "改善点を教えてください。主な理由は何でしたか？",
            "reason_too_expensive": "💰 高すぎる",
            "reason_not_using": "📱 あまり使わなかった",
            "reason_missing_features": "🔧 必要な機能がない",
            "reason_other": "💬 その他",
            "pause_heading": "休憩が必要？",
            "pause_message": "解約の代わりに30日間サブスクリプションを一時停止できます。",
            "pause_link": "一時停止する",
            "closing": "戻りたくなったら、いつでもドアは開いています。 💚",
        },
    },
    "zh": {
        "welcome": {
            "subject": "你的营养之旅从现在开始，{{first_name}}",
            "heading": "你的营养之旅从现在开始，{{first_name}}！ 🎉",
            "intro": "欢迎加入 Nutree！你已经迈出了了解营养、实现目标的第一步。",
            "target_label": "每日卡路里目标",
            "social_proof": "加入 10,000+ 用户，每天用 Nutree 记录饮食。",
            "cta": "记录第一餐",
            "closing": "一餐一餐来。你可以的！ 💪",
        },
        "reengagement": {
            "subject": "我们保存了你的进度，{{first_name}}",
            "heading": "我们保存了你的进度，{{first_name}} 📊",
            "intro": "我们注意到你已经有几天没有记录饮食了。你的连续记录和数据还在这里。",
            "streak_label": "天连续",
            "streak_warning": "别让它重置！",
            "cta": "从上次继续",
            "reply_note": "是什么阻碍了你？回复这封邮件 — 我们会阅读每一封。",
        },
        "trial_expiring": {
            "subject": "还有 {{days_left}} 天，你的宏量营养将不可见",
            "heading": "还有 {{days_left}} 天，你的宏量营养将不可见 ⏰",
            "intro": "你好 {{first_name}}，你的 Nutree 试用即将结束。",
            "stats_intro": "这是你目前的成果：",
            "meals_label": "已记录餐数",
            "streak_label": "天连续",
            "upgrade_message": "保留你的进度。立即升级，继续你的旅程。",
            "cta": "升级到 Premium",
        },
        "trial_cancelled": {
            "subject": "离开前 — 一个问题？",
            "heading": "离开前 — 一个问题？ 🤔",
            "intro": "你好 {{first_name}}，很遗憾看到你取消。",
            "feedback_intro": "我们想知道可以如何改进。主要原因是什么？",
            "reason_too_expensive": "💰 太贵",
            "reason_not_using": "📱 用得不够",
            "reason_missing_features": "🔧 缺少需要的功能",
            "reason_other": "💬 其他原因",
            "pause_heading": "需要休息一下？",
            "pause_message": "你可以暂停订阅 30 天，而不是取消。",
            "pause_link": "改为暂停",
            "closing": "如果你想回来，大门永远敞开。 💚",
        },
    },
}
