"""Read validated meal insights generated by the asynchronous Worker."""

from __future__ import annotations

import logging

from src.domain.ports.cache_port import CachePort
from src.domain.services.meal_value_insight_contract import (
    MealValueInsights,
    parse_ai_result,
)

logger = logging.getLogger(__name__)

MEAL_INSIGHT_CACHE_PREFIX = "meal_insight:"


class MealValueInsightService:
    """Cache reader for Worker-owned meal value insights."""

    @staticmethod
    def cache_key_for_meal(meal_id: str) -> str:
        """Return the Worker-owned cache key for a persisted meal."""
        return f"{MEAL_INSIGHT_CACHE_PREFIX}{meal_id}"

    @classmethod
    def cache_version_for_meal(cls, meal_id: str) -> str:
        """Return the stable cache identifier exposed by the status endpoint."""
        return cls.cache_key_for_meal(meal_id)

    async def get_cached_for_meal(
        self,
        *,
        meal_id: str,
        cache_service: CachePort | None,
    ) -> MealValueInsights | None:
        """Read the Worker-generated insight payload without invoking AI."""
        if cache_service is None:
            return None

        try:
            cached = await cache_service.get(self.cache_key_for_meal(meal_id))
        except Exception as exc:
            logger.info(
                "meal_value_insights.cache_read_failed meal_id=%s error=%s",
                meal_id,
                type(exc).__name__,
            )
            return None
        return parse_ai_result(cached)
