"""Add meal planner serving revision and recipe snapshots

Revision ID: 20260921145751448341
Revises: 20260921053202014838
Create Date: 2026-09-21 21:57:51.450149

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20260921145751448341"
down_revision: str | None = "20260921053202014838"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "meal",
        sa.Column("catalog_meal_content_hash", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "meal_catalog", sa.Column("base_servings", sa.Integer(), nullable=True)
    )
    op.add_column(
        "meal_catalog", sa.Column("serving_source", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "meal_catalog",
        sa.Column(
            "serving_confidence",
            sa.String(length=16),
            server_default="unknown",
            nullable=False,
        ),
    )
    op.add_column(
        "weekly_meal_plan_pantry_items",
        sa.Column("custom_unit", sa.String(length=80), nullable=True),
    )
    op.add_column(
        "weekly_meal_plans",
        sa.Column("revision", sa.Integer(), server_default="1", nullable=False),
    )
    op.create_check_constraint(
        "ck_meal_catalog_base_servings_positive",
        "meal_catalog",
        "base_servings IS NULL OR base_servings > 0",
    )
    op.create_check_constraint(
        "ck_meal_catalog_serving_confidence",
        "meal_catalog",
        "serving_confidence IN ('verified', 'estimated', 'unknown')",
    )
    op.create_check_constraint(
        "ck_weekly_meal_plan_revision",
        "weekly_meal_plans",
        "revision > 0",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_weekly_meal_plan_revision", "weekly_meal_plans", type_="check"
    )
    op.drop_constraint(
        "ck_meal_catalog_serving_confidence", "meal_catalog", type_="check"
    )
    op.drop_constraint(
        "ck_meal_catalog_base_servings_positive", "meal_catalog", type_="check"
    )
    op.drop_column("weekly_meal_plans", "revision")
    op.drop_column("weekly_meal_plan_pantry_items", "custom_unit")
    op.drop_column("meal_catalog", "serving_confidence")
    op.drop_column("meal_catalog", "serving_source")
    op.drop_column("meal_catalog", "base_servings")
    op.drop_column("meal", "catalog_meal_content_hash")
    # ### end Alembic commands ###
